name: "Issue"

on:
  issues:
    types: [opened]

jobs:
  issue:
    name: "Issue"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Create App Token"
        if: ${{ !github.event.release.prerelease }}
        id: app
        uses: actions/create-github-app-token@v2
        with:
          app-id: 146360
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: smashedr
          repositories: test5

      - name: "AI Issue"
        uses: smashedr/ai-issue-action@master
        env:
          GOOGLE_GENERATIVE_AI_API_KEY: ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY }}
        with:
          model: gemini-2.5-flash
          instructions: |
            You are an assistant responding to a GitHub Issue.
            The knowledge is from a VitePress documentation site using the base url:
            https://cssnr.github.io/cache-cleaner/
            Please respond to the issue using your knowledge of web extensions and this documentation:
          file: |
            AGENTS.md
            docs/**/*.md
          token: ${{ steps.app.outputs.token }}
