name: "Issue"

on:
  issues:
    types: [opened]

jobs:
  issue:
    name: "Issue"
    if: |
      contains(github.event.issue.labels.*.name, 'bug') ||
      github.event.issue.labels[0] == null

    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      contents: write
      issues: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Create App Token"
        id: app
        uses: actions/create-github-app-token@v3
        with:
          app-id: 146360
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: "AI Issue"
        #uses: smashedr/ai-issue-action@master
        uses: smashedr/test-action3@v2
        #env:
        #  GOOGLE_GENERATIVE_AI_API_KEY: ${{ secrets.GOOGLE_GENERATIVE_AI_API_KEY }}
        with:
          token: ${{ steps.app.outputs.token }}
          #model: gemini-2.5-flash
          model: big-pickle
          instructions: |
            You are a helpful assistant testing a successful AI response.
          path: |
            README.md
          tail: |
            _Response generated by the [AI Issue Action](https://github.com/smashedr/ai-issue-action)._
